[package]
name = "aeon-sync"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aeon-sync"
path = "src/main.rs"

[dependencies]
aeon-capture = { path = "../aeon-capture" }
axum = { version = "0.7", features = ["multipart", "ws"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs", "cors"] }
notify = "6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
blake3 = "1.5"
base64 = "0.22"
dirs = "5"
sysinfo = "0.30"
tracing = "0.1"
tracing-subscriber = "0.3"
mime_guess = "2"
indicatif = "0.17"
tokio-util = { version = "0.7", features = ["io"] }
aes-gcm = "0.10"
pbkdf2 = "0.12"
rand = "0.8"
sha2 = "0.10"

aeon-store = { path = "../aeon-store" }
