[package]
name = "aeon-vm"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "aeon-run"
path = "src/main.rs"

[[bin]]
name = "aeon-asm"
path = "src/bin/aeon-asm.rs"

[[bin]]
name = "aeon-recv"
path = "src/bin/aeon-recv.rs"

[[bin]]
name = "aeon-send"
path = "src/bin/aeon-send.rs"

[[bin]]
name = "aeon-forth"
path = "src/bin/aeon-forth.rs"

[[bin]]
name = "aeon"
path = "src/bin/aeon.rs"

[[bin]]
name = "aeon-daemon"
path = "src/bin/aeon-daemon.rs"

[[bin]]
name = "aeon-console"
path = "src/bin/aeon-console.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
blake3 = "1.5"
aeon-store = { path = "../aeon-store" }
cranelift = "0.109"
cranelift-frontend = "0.109"
cranelift-jit = "0.109"
cranelift-module = "0.109"
cranelift-native = "0.109"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "vm_benchmarks"
harness = false
